MENSA/ViewModels/OrderViewModel.cs
using MENSA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MENSA.ViewModels
{
    public class OrderViewModel
    {
        public NewNarudzba Order { get; set; }
        
        public List<MenuViewModel> menuVM { get; set; }
    }
}

MENSA/Controllers/CartController.cs
using MENSA.Data;
using MENSA.Helpers;
using MENSA.Models;
using MENSA.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace MENSA.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> userManager;

        public CartController(ApplicationDbContext db, UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
            _db = db;
        }

        [Route("Index")]
        public IActionResult Index()
        {
            var cart = SessionHelper.GetObjectFromJson<List<MenuViewModel>>(HttpContext.Session, "cart");
            ViewBag.cart = cart;

            if (cart != null)
            {
                ViewBag.total = cart.Sum(item => item.Menu.Price * item.Quantity);

            }
            else {
                ViewBag.total = 0;
            }
            
            return View();
        }

        public IActionResult Buy(int id)
        {
            //Menu meal  = _db.Menu.Where(a => a.Id == id).FirstOrDefault();
            //MenuViewModel mealVM = new MenuViewModel();
            //mealVM.Menu = meal;


            
            if (SessionHelper.GetObjectFromJson<List<MenuViewModel>>(HttpContext.Session, "cart") == null)
            {
                Menu meal = _db.Menu.Where(a => a.Id == id).FirstOrDefault();
                MenuViewModel mealVM = new MenuViewModel();
                mealVM.Menu = meal;

                List<MenuViewModel> cart = new List<MenuViewModel>();
                mealVM.Quantity = 1;
                cart.Add(mealVM);
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<MenuViewModel> cart = SessionHelper.GetObjectFromJson<List<MenuViewModel>>(HttpContext.Session, "cart");
                int index = isExist(id.ToString());
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    Menu meal = _db.Menu.Where(a => a.Id == id).FirstOrDefault();
                    MenuViewModel mealVM = new MenuViewModel();
                    mealVM.Menu = meal;

                    mealVM.Quantity = 1;
                    cart.Add(mealVM);
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            
            var menzaId = HttpContext.Session.GetInt32("currentMenzaId");
            return RedirectToAction("Select_Menu", "SelectMenza", new {ID = menzaId });
            
        }

        
        public IActionResult Remove(string id)
        {
            List<MenuViewModel> cart = SessionHelper.GetObjectFromJson<List<MenuViewModel>>(HttpContext.Session, "cart");
            int index = isExist(id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> ConfirmOrder()
        {
            List<MenuViewModel> cart = SessionHelper.GetObjectFromJson<List<MenuViewModel>>(HttpContext.Session, "cart");

            if (cart != null)
            {
                var currentMenzaId = HttpContext.Session.GetInt32("currentMenzaId");
                var currentMenza = _db.Menza.Find(currentMenzaId);

                var currentUser = await userManager.GetUserAsync(User);
                NewNarudzba newNarudzba = new NewNarudzba {MenzaId = (int)currentMenzaId ,Menza = currentMenza,Ready = false, Delivered = false, ApplicationUser = currentUser,StudentId = currentUser.Id };

                _db.NewNarudzba.Add(newNarudzba);
                _db.SaveChanges();

                int narudzbaId = newNarudzba.Id;

                foreach (var item in cart)
                {
                    for (int i = 0; i < item.Quantity; i++)
                    {

                        NewModel newModel = new NewModel {  NewNarudzbaId = narudzbaId, MenuId = item.Menu.Id };

                        _db.NewModel.Add(newModel);
                        _db.SaveChanges();
                    }

                }
                float priceTotal = cart.Sum(item => item.Menu.Price * item.Quantity);
                OrderNumberViewModel orderNumberVM = new OrderNumberViewModel { Narudzba = newNarudzba, Price = priceTotal };
                cart.Clear();
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);

                return View("OrderNumber", orderNumberVM);
            }

            return View("Index");
        }

        
        public IActionResult OrderNumber(OrderNumberViewModel currentNarudzba)
        {
            
            
            return View(currentNarudzba);
        }


        private int isExist(string id)
        {
            List<MenuViewModel> cart = SessionHelper.GetObjectFromJson<List<MenuViewModel>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Menu.Id.ToString().Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
    }
}

MENSA/Controllers/LogInController.cs
using MENSA.Data;
using MENSA.Models;
using MENSA.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MENSA.Controllers
{
    public class LogInController : Controller
    {
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly UserManager<ApplicationUser> userManager;


        //private readonly ILogger<LogInController> _logger;

        //public LogInController(ILogger<LogInController> logger)
        //{
        //    _logger = logger;
        //}

        public LogInController(SignInManager<ApplicationUser> signInManager, 
                                    UserManager<ApplicationUser> userManager)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        
        public IActionResult Index()
        {
            if (signInManager.IsSignedIn(User) && (User.IsInRole("Student") || User.IsInRole("Zaposlenik")))
            {
                return RedirectToAction("Index", "SelectMenza");
            }
            else if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
            {
                return RedirectToAction("Admin_functionalities", "Admin");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LogIn(LogInViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);
                


                if (result.Succeeded)
                {
                    var user = await signInManager.UserManager.FindByEmailAsync(model.Email);
                    IList<string> roles = await signInManager.UserManager.GetRolesAsync(user);

                    

                    if ( String.Equals(roles[0],"Student") || String.Equals(roles[0], "Zaposlenik"))
                    {
                        return RedirectToAction("Index", "SelectMenza");
                    }
                    else if (String.Equals(roles[0], "Admin"))
                    {
                        return RedirectToAction("Admin_functionalities", "Admin");
                    }
                }

                ModelState.AddModelError(string.Empty, "Invalid Login Attempt");
            }
            
            return View("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Login");
        }


        /*private readonly ApplicationDbContext _db;

       public LogInController(ApplicationDbContext db)
       {
           _db = db;
       }*/
        /*//Post - login
        [HttpPost]
        [ValidateAntiForgeryToken] //za sigurnost(da podaci nisu promijenjeni od submitanja podataka do dolaska ovde)
        public IActionResult LogIn(Student obj)
        {
            var emailParamater = new SqlParameter("@Email", obj.Email);
            var passwordParametar = new SqlParameter("@Password", obj.Password);
            var tempStudent = _db.Student.FromSqlRaw("SELECT * FROM Student WHERE Email=@Email AND Password=@Password", emailParamater, passwordParametar).FirstOrDefault();

            //tempStudent - student koji se logira

            if (tempStudent != null)
            {
             
                return RedirectToAction("Index", "SelectMenza");
            }
            else
            {
                return View("Index");
            }
            
        }Za oni jednostavni unos  */


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MENSA/Controllers/SelectMenzaController.cs
using MENSA.Data;
using MENSA.Helpers;
using MENSA.Models;
using MENSA.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MENSA.Controllers
{
    public class SelectMenzaController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ApplicationDbContext _db;

        public SelectMenzaController(ApplicationDbContext db, UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Menza> objList = _db.Menza;

            return View(objList);
        }

        
        [HttpGet]
        public IActionResult Select_menu(int ID)
        {
            HttpContext.Session.SetInt32("currentMenzaId", ID);
            var currentMenza = _db.Menza.Where(a => a.Id == ID).FirstOrDefault();
            HttpContext.Session.SetString("currentMenzaName", currentMenza.Name);

            var menzaMeals = (from mm in _db.Menza_Menu
                              join me in _db.Menu on mm.MenuId equals me.Id
                              where mm.MenzaId == ID && mm.Availability == true
                              select new Menu
                              {
                                  Id = me.Id,
                                  Name = me.Name,
                                  PicturePath = me.PicturePath,
                                  Price = me.Price
                              }).ToList();

            
            return View(menzaMeals);
        }

        

        public async Task<IActionResult> Orders(int ID)
        {
            var currentOrders = _db.NewNarudzba.Where(o => o.MenzaId == ID); //dohvaca narudzbe za menzu

            List<OrderViewModel> ordersVM = new List<OrderViewModel>(); //ovo cemo poslati viewu
            
            int i = 0;

            foreach (var item in currentOrders)
            {
                var orderUser = await userManager.FindByIdAsync(item.StudentId);
                item.ApplicationUser = orderUser; //dohvaca korisnika narudzbe ------------------------------>ne radi, triba popravit nekako

                ordersVM.Add(new OrderViewModel {Order = item });
                ordersVM[i].menuVM = new List<MenuViewModel>();

                var newModels = _db.NewModel.Where(m => m.NewNarudzbaId == item.Id); //dohvaca sva jela za tu narudzbu

                foreach (var obj in newModels)
                {
                    var meal = _db.Menu.Where(m => m.Id == obj.MenuId).FirstOrDefault();
                    MenuViewModel tempMenuVm = new MenuViewModel { Menu = meal, Quantity = 1 };

                    bool containsItem = ordersVM[i].menuVM.Any(x => x.Menu.Id == meal.Id);

                    if (containsItem == true)
                    {
                        int index = ordersVM[i].menuVM.FindIndex(x => x.Menu.Id == meal.Id);
                        ordersVM[i].menuVM[index].Quantity++;
                    }
                    else {
                        ordersVM[i].menuVM.Add(tempMenuVm);

                    }

                    
                }
                i++;
            }
            

            return View(ordersVM);
        }

    }
}

MENSA/Views/SelectMenza/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> signInManager;
@model IEnumerable<MENSA.Models.Menza>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/select_menza_styles.css">
    <title>MENSA</title>
</head>
<body>
    <header class="header">
        <div class="title-logo">
            <h1 class="title">MENSA</h1>
            <img class="header-logo" src="/assets/burger.png" alt="Logo">
        </div>
   @if (signInManager.IsSignedIn(User))@*@User.Identity.Name triba dodat *@
    {
    <div class="user-wrapper">
        <div class="user-id">@User.Identity.Name</div>
        <div class="dropdown">
            <img class="header-user" src="/assets/user.png" alt="User settings">
            <div class="dropdown-menu">
                <div class="logout-wrap">
                    <img class="logout" src="/assets/logout2.png" alt="Log out">
                </div>
                <form method="post" asp-action="Logout" asp-controller="LogIn">
                    <button type="submit" style="width:auto" class="login-button">Odjavi se</button>
                </form>
            </div>
        </div>
    </div>
    }
    </header>
        <main>
            <article class="article-wrapper">
                <h1 class="article-title">Menze SCST</h1>
                <p class="article-description">Odaberi menzu čiju ponudu želiš vidjeti!</p>
            </article>
            <div class="list-wrapper">
                @foreach (var obj in Model)
                {
                    if (User.IsInRole("Student"))
                    {
                        <a asp-action="Select_menu" asp-route-id="@obj.Id" class="box lightblue">
                        <h3>@obj.Name</h3>
                        <img class="canteen-img" src="@("/assets/" +obj.PicturePath)" alt="FEB menza">
                        </a>
                    }
                    else
                    { 
                        <a asp-action="Orders" asp-route-id="@obj.Id" class="box lightblue">
                        <h3>@obj.Name</h3>
                        <img class="canteen-img" src="@("/assets/" +obj.PicturePath)" alt="FEB menza">
                        </a>
                    }
                    
                    
                    
                }

                @*<a href="" class="box lightblue">
                    <h3>FESB - STOP</h3>
                    <img class="canteen-img" src="/assets/fesb-donja.jpg" alt="FESB STOP menza">
                </a>
                <a href="" class="box lightgray">
                    <h3>FESB</h3>
                    <img class="canteen-img" src="/assets/fesb-gornja.jpg" alt="FESB menza">
                </a>
                <a href="" class="box lightblue">
                    <h3>Ekonomski Fakultet</h3>
                    <img class="canteen-img" src="/assets/ekonomija.jpg" alt="Ekonomski Fakultet menza">
                </a>
                <a href="" class="box lightgray">
                    <h3>Kampus</h3>
                    <img class="canteen-img" src="/assets/kampus.jpg" alt="Kampus menza">
                </a>
                <a href="" class="box lightgray">
                    <h3>Medicinski Fakultet</h3>
                    <img class="canteen-img" src="/assets/medicina.jpg" alt="Medicinski Fakultet menza">
                </a>
                <a href="" class="box lightblue">
                    <h3>Gradevinski fakultet</h3>
                    <img class="canteen-img" src="/assets/fgag.jpg" alt="Gradevinski Fakultet menza">
                </a>
                <a href="" class="box lightgray">
                    <h3>Index</h3>
                    <img class="canteen-img" src="/assets/index.jpg" alt="Index menza">
                </a>
                <a href="" class="box lightblue">
                    <h3>Spinut</h3>
                    <img class="canteen-img" src="/assets/spinut.jpg" alt="Spinut menza">
                </a>*@
            </div>
        </main>
        <script src="/js/select-menza-screen.js"></script>
    </body>

</html>

MENSA/Views/SelectMenza/Orders.cshtml
@model IEnumerable<MENSA.ViewModels.OrderViewModel>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pregled narudžbi</title>
    <link rel="stylesheet" href="~/css/font-awesome.min.css" />
    <link rel="stylesheet" href="/css/orders_style.css" />
</head>
<body>
    <header class="header">
        <div class="title-logo">
            <h1 class="title">MENSA</h1>
            <img class="header-logo" src="/assets/burger.png" alt="Logo" />
        </div>
        <div class="user-wrapper">
            <div class="user-id">@User.Identity.Name</div>
            <div class="dropdown">
                <img class="header-user" src="/assets/user.png" alt="User settings" />
                <div class="dropdown-menu">
                    <div class="logout-wrap">
                        <img class="logout" src="/assets/logout2.png" alt="Log out" />
                    </div>
                    <form method="post" asp-action="Logout" asp-controller="LogIn">
                        <button type="submit" style="width:auto" class="login-button">Odjavi se</button>
                    </form>
                </div>
            </div>
        </div>
    </header>

    <main>
        <h1 class="title-2">PREGLED NARUDŽBI</h1>

        <div id="cards-container">
            @foreach (var obj in Model)
            {
            <article class="card">
                <i class="fa fa-times delete-button clickable-icon"></i>
                <h3>
                    <span class="order-number">Narudžba broj: @obj.Order.Id</span>
                </h3>

                <table>
                    <thead>
                        <tr>
                            <th>PROIZVOD</th>
                            <th>KOLIČINA</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in obj.menuVM)
                        {
                            <tr>
                                <td>@item.Menu.Name</td>
                                <td>@item.Quantity</td>
                            </tr>
                        }

                    </tbody>
                </table>
                <div class="checkbox-container">
                    <input type="checkbox" id="checkbox" name="checkbox" />
                    <label class="checkbox-label" for="checkbox">Narudžba spremna</label>
                </div>
            </article>
            }


                    @*<article class="card">
                    <i class="fa fa-times delete-button clickable-icon"></i>
                    <h3>
                        <span class="order-number">Narudžba broj: 23</span>
                    </h3>

                    <table>
                        <thead>
                            <tr>
                                <th>PROIZVOD&#160</th>
                                <th>KOLIČINA</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Pomfrit</td>
                                <td>2</td>
                            </tr>
                        </tbody>
                    </table>

                    <div class="checkbox-container">
                        <input type="checkbox" id="checkbox" name="checkbox" />
                        <label class="checkbox-label" for="checkbox">Narudžba spremna</label>
                    </div>
                </article>

                <article class="card">
                    <i class="fa fa-times delete-button clickable-icon"></i>
                    <h3>
                        <span class="order-number">Narudžba broj: 24</span>
                    </h3>

                    <table>
                        <thead>
                            <tr>
                                <th>PROIZVOD</th>
                                <th>KOLIČINA</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Pomfrit</td>
                                <td>2</td>
                            </tr>
                        </tbody>
                    </table>

                    <div class="checkbox-container">
                        <input type="checkbox" id="checkbox" name="checkbox" />
                        <label class="checkbox-label" for="checkbox">Narudžba spremna</label>
                    </div>
                </article>

                <article class="card">
                    <i class="fa fa-times delete-button clickable-icon"></i>
                    <h3>
                        <span class="order-number">Narudžba broj: 25</span>
                    </h3>

                    <table>
                        <thead>
                            <tr>
                                <th>PROIZVOD</th>
                                <th>KOLIČINA</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Sok od naranče</td>
                                <td>1</td>
                            </tr>
                            <tr>
                                <td>Banana</td>
                                <td>2</td>
                            </tr>
                        </tbody>
                    </table>

                    <div class="checkbox-container">
                        <input type="checkbox" id="checkbox" name="checkbox" />
                        <label class="checkbox-label" for="checkbox">Narudžba spremna</label>
                    </div>
                </article>

                <article class="card">
                    <i class="fa fa-times delete-button clickable-icon"></i>
                    <h3>
                        <span class="order-number">Narudžba broj: 26</span>
                    </h3>

                    <table>
                        <thead>
                            <tr>
                                <th>PROIZVOD</th>
                                <th>KOLIČINA</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Pomfrit</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>Meso</td>
                                <td>1</td>
                            </tr>
                            <tr>
                                <td>Sladoled</td>
                                <td>3</td>
                            </tr>
                            <tr>
                                <td>Sladoled</td>
                                <td>3</td>
                            </tr>

                        </tbody>
                    </table>

                    <div class="checkbox-container">
                        <input type="checkbox" id="checkbox" name="checkbox" />
                        <label class="checkbox-label" for="checkbox">Narudžba spremna</label>
                    </div>
                </article>

                <article class="card">
                    <i class="fa fa-times delete-button clickable-icon"></i>
                    <h3>
                        <span class="order-number">Narudžba broj: 27</span>
                    </h3>

                    <table>
                        <thead>
                            <tr>
                                <th>PROIZVOD&#160</th>
                                <th>KOLIČINA</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Pomfrit</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>Voda</td>
                                <td>1</td>
                            </tr>
                        </tbody>
                    </table>

                    <div class="checkbox-container">
                        <input type="checkbox" id="checkbox" name="checkbox" />
                        <label class="checkbox-label" for="checkbox">Narudžba spremna</label>
                    </div>
                </article>*@
            </div>
    </main>

    <script src="/js/orders.js"></script>
    <script src="~/js/select-menza-screen.js"></script>
</body>
</html>

MENSA/Views/SelectMenza/Select_Menu.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<ApplicationUser> signInManager;
@model IEnumerable<MENSA.Models.Menu>

<!DOCTYPE html>
<html lagn="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/select_menu_styles.css">
    <title>MENSA</title>
</head>
<body>

    <header class="header">
        <div class="title-logo">
            <h1 class="title">MENSA</h1>
            <img class="header-logo" src="/assets/burger.png" alt="Logo">
        </div>
        <div class="user-wrapper">
            <div class="user-id">@User.Identity.Name</div>
            <div class="dropdown">
                <img class="header-user" src="/assets/user.png" alt="User settings">
                <div class="dropdown-menu">
                    <div class="logout-wrap">
                        <img class="logout" src="/assets/logout2.png" alt="Log out">
                    </div>
                    <form method="post" asp-action="Logout" asp-controller="LogIn">
                        <button type="submit" style="width:auto" class="login-button">Odjavi se</button>
                    </form>
                </div>
            </div>
</header>
    <main>
        <article class="article-wrapper">
            <h1 class="article-title">Dnevni jelovnik menze</h1>
        </article>
        <div class="main-div">
            <div class="menu-wrapper">

                <div class="box lightgray">
                    <h2>Dnevna ponuda</h2>
                    <h3 class="menu1"> MENU 1</h3>
                    <ul>
                        <li>Bolognese</li>
                        <li>Mađarica</li>
                        <li>Sokić</li>
                    </ul>
                </div>
            </div>
            <div class="list-wrapper">
                @foreach (var obj in Model)
                {
                    <div class="box lightblue">
                        <h3>@obj.Name</h3>

                        <img class="article-img" src="@("/assets/"+@obj.PicturePath)" alt="6 kn">
                        <p>@obj.Price kn</p>
                        <a asp-controller="cart" asp-action="buy" asp-route-id="@obj.Id" class="buying">Dodaj u košaricu</a>
                    </div>
                }

                @*<div class="box lightblue">
            <h3>Pomfrit</h3>

            <img class="article-img" src="/assets/pomfrit.jpg" alt="4 kn">
            <p>4 kn</p>
            <a href="" class="buying">BUY NOW</a>

        </div>
        <div class="box lightblue">
            <h3>Bolognese</h3>

            <img class="article-img" src="/assets/bolognese.jfif" alt="6 kn">
            <p>6 kn</p>
            <a href="" class="buying">BUY NOW</a>
        </div>
        <div class="box lightblue">
            <h3>Pizza</h3>

            <img class="article-img" src="/assets/pizza.jpg" alt="5 kn">
            <p>5 kn</p>
            <a href="" class="buying">BUY NOW</a>
        </div>*@
            </div>
            
                <div class="box lightgray">
                    <h2> Radno vrijeme menze </h2>
                    <p>Ponedjeljak - Petak : 07-21</p>
                    <p>Subota -Nedjelja : 07-16</p>
                    <p>Kontakt broj : xxxxxxxxxx</p>
                    <a asp-action="Index" asp-controller="Cart"><img class="article-kosarica" src="/assets/kosarica.png" alt="Pregled košarice"></a>

                </div>
            
        </div>



    </main>

    <script src="~/js/select-menza-screen.js"></script>
</body>


</html>